# Generated by Django 5.0.4 on 2024-05-23 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('hours_lecture', models.IntegerField(blank=True, null=True)),
                ('hours_tutorial', models.IntegerField(blank=True, null=True)),
                ('hours_lab', models.IntegerField(blank=True, null=True)),
                ('pre_requisite', models.TextField(blank=True, null=True)),
                ('ects_credit', models.CharField(blank=True, max_length=255, null=True)),
                ('total_credits', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('ects_credits', models.CharField(blank=True, max_length=255, null=True)),
                ('grades', models.CharField(blank=True, max_length=255, null=True)),
                ('credits', models.CharField(blank=True, max_length=255, null=True)),
                ('grade_points', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewCatalog',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.course')),
            ],
            bases=('ease.course',),
        ),
        migrations.CreateModel(
            name='OldCatalog',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.course')),
            ],
            bases=('ease.course',),
        ),
    ]
