# Generated by Django 5.0.4 on 2024-07-09 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineering_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, max_length=255, null=True)),
                ('course_code', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('hours_lecture', models.IntegerField(blank=True, null=True)),
                ('hours_tutorial', models.IntegerField(blank=True, null=True)),
                ('hours_lab', models.IntegerField(blank=True, null=True)),
                ('pre_requisite', models.TextField(blank=True, null=True)),
                ('ects_credit', models.CharField(blank=True, max_length=255, null=True)),
                ('total_credits', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Architecture_and_Fine_Arts_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('hours_lecture', models.IntegerField(blank=True, null=True)),
                ('hours_tutorial', models.IntegerField(blank=True, null=True)),
                ('hours_lab', models.IntegerField(blank=True, null=True)),
                ('pre_requisite', models.TextField(blank=True, null=True)),
                ('ects_credit', models.CharField(blank=True, max_length=255, null=True)),
                ('total_credits', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AreaTechnicalElectiveCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('hours_lecture', models.IntegerField(blank=True, null=True)),
                ('hours_tutorial', models.IntegerField(blank=True, null=True)),
                ('hours_lab', models.IntegerField(blank=True, null=True)),
                ('pre_requisite', models.TextField(blank=True, null=True)),
                ('ects_credit', models.CharField(blank=True, max_length=255, null=True)),
                ('total_credits', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Arts_and_Sciences_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('hours_lecture', models.IntegerField(blank=True, null=True)),
                ('hours_tutorial', models.IntegerField(blank=True, null=True)),
                ('hours_lab', models.IntegerField(blank=True, null=True)),
                ('pre_requisite', models.TextField(blank=True, null=True)),
                ('ects_credit', models.CharField(blank=True, max_length=255, null=True)),
                ('total_credits', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Economics_and_Administrative_Sciences_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('hours_lecture', models.IntegerField(blank=True, null=True)),
                ('hours_tutorial', models.IntegerField(blank=True, null=True)),
                ('hours_lab', models.IntegerField(blank=True, null=True)),
                ('pre_requisite', models.TextField(blank=True, null=True)),
                ('ects_credit', models.CharField(blank=True, max_length=255, null=True)),
                ('total_credits', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dentistry_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('hours_lecture', models.IntegerField(blank=True, null=True)),
                ('hours_tutorial', models.IntegerField(blank=True, null=True)),
                ('hours_lab', models.IntegerField(blank=True, null=True)),
                ('pre_requisite', models.TextField(blank=True, null=True)),
                ('ects_credit', models.CharField(blank=True, max_length=255, null=True)),
                ('total_credits', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Educational_Sciences_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('hours_lecture', models.IntegerField(blank=True, null=True)),
                ('hours_tutorial', models.IntegerField(blank=True, null=True)),
                ('hours_lab', models.IntegerField(blank=True, null=True)),
                ('pre_requisite', models.TextField(blank=True, null=True)),
                ('ects_credit', models.CharField(blank=True, max_length=255, null=True)),
                ('total_credits', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Health_Sciences_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('hours_lecture', models.IntegerField(blank=True, null=True)),
                ('hours_tutorial', models.IntegerField(blank=True, null=True)),
                ('hours_lab', models.IntegerField(blank=True, null=True)),
                ('pre_requisite', models.TextField(blank=True, null=True)),
                ('ects_credit', models.CharField(blank=True, max_length=255, null=True)),
                ('total_credits', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Law_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('hours_lecture', models.IntegerField(blank=True, null=True)),
                ('hours_tutorial', models.IntegerField(blank=True, null=True)),
                ('hours_lab', models.IntegerField(blank=True, null=True)),
                ('pre_requisite', models.TextField(blank=True, null=True)),
                ('ects_credit', models.CharField(blank=True, max_length=255, null=True)),
                ('total_credits', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phamarcy_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('hours_lecture', models.IntegerField(blank=True, null=True)),
                ('hours_tutorial', models.IntegerField(blank=True, null=True)),
                ('hours_lab', models.IntegerField(blank=True, null=True)),
                ('pre_requisite', models.TextField(blank=True, null=True)),
                ('ects_credit', models.CharField(blank=True, max_length=255, null=True)),
                ('total_credits', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('ects_credits', models.CharField(blank=True, max_length=255, null=True)),
                ('grades', models.CharField(blank=True, max_length=255, null=True)),
                ('credits', models.CharField(blank=True, max_length=255, null=True)),
                ('grade_points', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AI_Catalog',
            fields=[
                ('engineering_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.engineering_course')),
            ],
            bases=('ease.engineering_course',),
        ),
        migrations.CreateModel(
            name='Civil_Newcatalog',
            fields=[
                ('engineering_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.engineering_course')),
            ],
            bases=('ease.engineering_course',),
        ),
        migrations.CreateModel(
            name='civil_OldCatalog',
            fields=[
                ('engineering_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.engineering_course')),
            ],
            bases=('ease.engineering_course',),
        ),
        migrations.CreateModel(
            name='Computer_Newcatalog',
            fields=[
                ('engineering_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.engineering_course')),
            ],
            bases=('ease.engineering_course',),
        ),
        migrations.CreateModel(
            name='Computer_OldCatalog',
            fields=[
                ('engineering_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.engineering_course')),
            ],
            bases=('ease.engineering_course',),
        ),
        migrations.CreateModel(
            name='EE_Newcatalog',
            fields=[
                ('engineering_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.engineering_course')),
            ],
            bases=('ease.engineering_course',),
        ),
        migrations.CreateModel(
            name='EE_OldCatalog',
            fields=[
                ('engineering_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.engineering_course')),
            ],
            bases=('ease.engineering_course',),
        ),
        migrations.CreateModel(
            name='Software_Newcatalog',
            fields=[
                ('engineering_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.engineering_course')),
            ],
            bases=('ease.engineering_course',),
        ),
        migrations.CreateModel(
            name='Software_Oldcatalog',
            fields=[
                ('engineering_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.engineering_course')),
            ],
            bases=('ease.engineering_course',),
        ),
        migrations.CreateModel(
            name='archi_New_catalog',
            fields=[
                ('architecture_and_fine_arts_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.architecture_and_fine_arts_course')),
            ],
            bases=('ease.architecture_and_fine_arts_course',),
        ),
        migrations.CreateModel(
            name='archi_Old_catalog',
            fields=[
                ('architecture_and_fine_arts_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.architecture_and_fine_arts_course')),
            ],
            bases=('ease.architecture_and_fine_arts_course',),
        ),
        migrations.CreateModel(
            name='interior_New_catalog',
            fields=[
                ('architecture_and_fine_arts_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.architecture_and_fine_arts_course')),
            ],
            bases=('ease.architecture_and_fine_arts_course',),
        ),
        migrations.CreateModel(
            name='interior_Old_catalog',
            fields=[
                ('architecture_and_fine_arts_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.architecture_and_fine_arts_course')),
            ],
            bases=('ease.architecture_and_fine_arts_course',),
        ),
        migrations.CreateModel(
            name='Psychologyy_Turkish_New_catalog',
            fields=[
                ('arts_and_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.arts_and_sciences_course')),
            ],
            bases=('ease.arts_and_sciences_course',),
        ),
        migrations.CreateModel(
            name='Psychologyy_Turkish_Old_catalog',
            fields=[
                ('arts_and_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.arts_and_sciences_course')),
            ],
            bases=('ease.arts_and_sciences_course',),
        ),
        migrations.CreateModel(
            name='Psycholoy_English_New_catalog',
            fields=[
                ('arts_and_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.arts_and_sciences_course')),
            ],
            bases=('ease.arts_and_sciences_course',),
        ),
        migrations.CreateModel(
            name='Psycholoy_English_Old_catalog',
            fields=[
                ('arts_and_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.arts_and_sciences_course')),
            ],
            bases=('ease.arts_and_sciences_course',),
        ),
        migrations.CreateModel(
            name='BA_New_catalog',
            fields=[
                ('economics_and_administrative_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.economics_and_administrative_sciences_course')),
            ],
            bases=('ease.economics_and_administrative_sciences_course',),
        ),
        migrations.CreateModel(
            name='BA_Old_catalog',
            fields=[
                ('economics_and_administrative_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.economics_and_administrative_sciences_course')),
            ],
            bases=('ease.economics_and_administrative_sciences_course',),
        ),
        migrations.CreateModel(
            name='BAM_catalog',
            fields=[
                ('economics_and_administrative_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.economics_and_administrative_sciences_course')),
            ],
            bases=('ease.economics_and_administrative_sciences_course',),
        ),
        migrations.CreateModel(
            name='BE_catalog',
            fields=[
                ('economics_and_administrative_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.economics_and_administrative_sciences_course')),
            ],
            bases=('ease.economics_and_administrative_sciences_course',),
        ),
        migrations.CreateModel(
            name='BFA_New_catalog',
            fields=[
                ('economics_and_administrative_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.economics_and_administrative_sciences_course')),
            ],
            bases=('ease.economics_and_administrative_sciences_course',),
        ),
        migrations.CreateModel(
            name='BFA_Old_catalog',
            fields=[
                ('economics_and_administrative_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.economics_and_administrative_sciences_course')),
            ],
            bases=('ease.economics_and_administrative_sciences_course',),
        ),
        migrations.CreateModel(
            name='Econo_catalog',
            fields=[
                ('economics_and_administrative_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.economics_and_administrative_sciences_course')),
            ],
            bases=('ease.economics_and_administrative_sciences_course',),
        ),
        migrations.CreateModel(
            name='IFB_New_catalog',
            fields=[
                ('economics_and_administrative_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.economics_and_administrative_sciences_course')),
            ],
            bases=('ease.economics_and_administrative_sciences_course',),
        ),
        migrations.CreateModel(
            name='IFB_Old_catalog',
            fields=[
                ('economics_and_administrative_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.economics_and_administrative_sciences_course')),
            ],
            bases=('ease.economics_and_administrative_sciences_course',),
        ),
        migrations.CreateModel(
            name='ITB_New_catalog',
            fields=[
                ('economics_and_administrative_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.economics_and_administrative_sciences_course')),
            ],
            bases=('ease.economics_and_administrative_sciences_course',),
        ),
        migrations.CreateModel(
            name='ITB_Old_catalog',
            fields=[
                ('economics_and_administrative_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.economics_and_administrative_sciences_course')),
            ],
            bases=('ease.economics_and_administrative_sciences_course',),
        ),
        migrations.CreateModel(
            name='MarkDigM_catalog',
            fields=[
                ('economics_and_administrative_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.economics_and_administrative_sciences_course')),
            ],
            bases=('ease.economics_and_administrative_sciences_course',),
        ),
        migrations.CreateModel(
            name='MIS_New_catalog',
            fields=[
                ('economics_and_administrative_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.economics_and_administrative_sciences_course')),
            ],
            bases=('ease.economics_and_administrative_sciences_course',),
        ),
        migrations.CreateModel(
            name='MIS_Old_catalog',
            fields=[
                ('economics_and_administrative_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.economics_and_administrative_sciences_course')),
            ],
            bases=('ease.economics_and_administrative_sciences_course',),
        ),
        migrations.CreateModel(
            name='PSIR_New_catalog',
            fields=[
                ('economics_and_administrative_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.economics_and_administrative_sciences_course')),
            ],
            bases=('ease.economics_and_administrative_sciences_course',),
        ),
        migrations.CreateModel(
            name='PSIR_Old_catalog',
            fields=[
                ('economics_and_administrative_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.economics_and_administrative_sciences_course')),
            ],
            bases=('ease.economics_and_administrative_sciences_course',),
        ),
        migrations.CreateModel(
            name='Dent_English_catalog',
            fields=[
                ('dentistry_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.dentistry_course')),
            ],
            bases=('ease.dentistry_course',),
        ),
        migrations.CreateModel(
            name='Dent_Turkish_catalog',
            fields=[
                ('dentistry_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.dentistry_course')),
            ],
            bases=('ease.dentistry_course',),
        ),
        migrations.CreateModel(
            name='Edu_ELT2018_catalog',
            fields=[
                ('educational_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.educational_sciences_course')),
            ],
            bases=('ease.educational_sciences_course',),
        ),
        migrations.CreateModel(
            name='Edu_ELT2021_catalog',
            fields=[
                ('educational_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.educational_sciences_course')),
            ],
            bases=('ease.educational_sciences_course',),
        ),
        migrations.CreateModel(
            name='Edu_ELT_catalog',
            fields=[
                ('educational_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.educational_sciences_course')),
            ],
            bases=('ease.educational_sciences_course',),
        ),
        migrations.CreateModel(
            name='Edu_GPC2018_catalog',
            fields=[
                ('educational_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.educational_sciences_course')),
            ],
            bases=('ease.educational_sciences_course',),
        ),
        migrations.CreateModel(
            name='Edu_GPC2021_catalog',
            fields=[
                ('educational_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.educational_sciences_course')),
            ],
            bases=('ease.educational_sciences_course',),
        ),
        migrations.CreateModel(
            name='Edu_GPC_catalog',
            fields=[
                ('educational_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.educational_sciences_course')),
            ],
            bases=('ease.educational_sciences_course',),
        ),
        migrations.CreateModel(
            name='Edu_PE2018_catalog',
            fields=[
                ('educational_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.educational_sciences_course')),
            ],
            bases=('ease.educational_sciences_course',),
        ),
        migrations.CreateModel(
            name='Edu_PE2021_catalog',
            fields=[
                ('educational_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.educational_sciences_course')),
            ],
            bases=('ease.educational_sciences_course',),
        ),
        migrations.CreateModel(
            name='Edu_PE_catalog',
            fields=[
                ('educational_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.educational_sciences_course')),
            ],
            bases=('ease.educational_sciences_course',),
        ),
        migrations.CreateModel(
            name='Edu_PFCP_catalog',
            fields=[
                ('educational_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.educational_sciences_course')),
            ],
            bases=('ease.educational_sciences_course',),
        ),
        migrations.CreateModel(
            name='Edu_SET2018_catalog',
            fields=[
                ('educational_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.educational_sciences_course')),
            ],
            bases=('ease.educational_sciences_course',),
        ),
        migrations.CreateModel(
            name='Edu_SET2021_catalog',
            fields=[
                ('educational_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.educational_sciences_course')),
            ],
            bases=('ease.educational_sciences_course',),
        ),
        migrations.CreateModel(
            name='Edu_TLT2018_catalog',
            fields=[
                ('educational_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.educational_sciences_course')),
            ],
            bases=('ease.educational_sciences_course',),
        ),
        migrations.CreateModel(
            name='Edu_TLT2021_catalog',
            fields=[
                ('educational_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.educational_sciences_course')),
            ],
            bases=('ease.educational_sciences_course',),
        ),
        migrations.CreateModel(
            name='Edu_TLT_catalog',
            fields=[
                ('educational_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.educational_sciences_course')),
            ],
            bases=('ease.educational_sciences_course',),
        ),
        migrations.CreateModel(
            name='nursing_catalog',
            fields=[
                ('health_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.health_sciences_course')),
            ],
            bases=('ease.health_sciences_course',),
        ),
        migrations.CreateModel(
            name='nutrition_catalog',
            fields=[
                ('health_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.health_sciences_course')),
            ],
            bases=('ease.health_sciences_course',),
        ),
        migrations.CreateModel(
            name='physiotherapy_engl_catalog',
            fields=[
                ('health_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.health_sciences_course')),
            ],
            bases=('ease.health_sciences_course',),
        ),
        migrations.CreateModel(
            name='physiotherapy_turk_new_catalog',
            fields=[
                ('health_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.health_sciences_course')),
            ],
            bases=('ease.health_sciences_course',),
        ),
        migrations.CreateModel(
            name='physiotherapy_turk_old_catalog',
            fields=[
                ('health_sciences_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.health_sciences_course')),
            ],
            bases=('ease.health_sciences_course',),
        ),
        migrations.CreateModel(
            name='Int_Law_New_catalog',
            fields=[
                ('law_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.law_course')),
            ],
            bases=('ease.law_course',),
        ),
        migrations.CreateModel(
            name='Int_Law_Old_catalog',
            fields=[
                ('law_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.law_course')),
            ],
            bases=('ease.law_course',),
        ),
        migrations.CreateModel(
            name='Law_New_catalog',
            fields=[
                ('law_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.law_course')),
            ],
            bases=('ease.law_course',),
        ),
        migrations.CreateModel(
            name='Law_Old_catalog',
            fields=[
                ('law_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.law_course')),
            ],
            bases=('ease.law_course',),
        ),
        migrations.CreateModel(
            name='Pharmay_English_Mpharm_catalog',
            fields=[
                ('phamarcy_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.phamarcy_course')),
            ],
            bases=('ease.phamarcy_course',),
        ),
        migrations.CreateModel(
            name='Pharmay_English_PharmD_catalog',
            fields=[
                ('phamarcy_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.phamarcy_course')),
            ],
            bases=('ease.phamarcy_course',),
        ),
        migrations.CreateModel(
            name='Pharmay_Turkish_catalog',
            fields=[
                ('phamarcy_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.phamarcy_course')),
            ],
            bases=('ease.phamarcy_course',),
        ),
        migrations.CreateModel(
            name='Pharmay_Turkish_English_PharmD_catalog',
            fields=[
                ('phamarcy_course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ease.phamarcy_course')),
            ],
            bases=('ease.phamarcy_course',),
        ),
    ]
