# Generated by Django 5.0.4 on 2024-05-13 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('hours_lecture', models.IntegerField()),
                ('hours_tutorial', models.IntegerField()),
                ('hours_lab', models.IntegerField()),
                ('pre_requisite', models.TextField()),
                ('ects_credit', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Course',
            new_name='NewCatalog',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='course',
        ),
        migrations.AddField(
            model_name='transcript',
            name='courseN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ease.newcatalog'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='is_old_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transcript',
            name='courseO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ease.oldcatalog'),
        ),
    ]
