# Generated by Django 5.0.4 on 2024-05-07 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ease', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_registration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transcript',
            name='date_of_graduation',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
