# Generated by Django 5.0.4 on 2024-05-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ease', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='course_new',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='course_old',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='is_old_course',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='student',
        ),
        migrations.AddField(
            model_name='transcript',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='credits',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
