# Generated by Django 5.0.4 on 2024-05-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ease', '0002_oldcatalog_rename_course_newcatalog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('hours_lecture', models.IntegerField()),
                ('hours_tutorial', models.IntegerField()),
                ('hours_lab', models.IntegerField()),
                ('pre_requisite', models.TextField()),
                ('ects_credit', models.IntegerField()),
                ('total_credits', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='newcatalog',
            name='total_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='courseO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ease.oldcurriculum'),
        ),
        migrations.DeleteModel(
            name='OldCatalog',
        ),
    ]
