# Generated by Django 5.0.4 on 2024-09-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ease', '0002_areaelectivecourse_archi_newcatalog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phamarcy_course',
            name='grade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
