# Generated by Django 5.0.4 on 2024-05-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ease', '0002_remove_transcript_course_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grade_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
